/*
OPERADORES ARITMÉTICOS

 + (SOMA)
 - (SUBTRAIR)
 * (MULTIPLICAR)
 / (DIVIDIR)
 % (MODULO) = RESTO DA DIVISAO

*/

SELECT 1 + 1 AS ADICAO
SELECT 5 - 10 AS [SUBTRACAI(-1)]
SELECT (2 + 7) * 10 AS MULTIPLICACAO
SELECT 90 / 3 AS DIVISAO
SELECT 90 / 60 AS DIV2
SELECT 90 % 60 AS [RESTO DA DIVISAO]

SELECT 1 + '1' AS SOMA
SELECT '1' + 1
SELECT '1' + '1' AS SOMA -- SINAL DE SOMA(+) COM TEXTOS SERÁ UMA CONCATENAÇÃO

SELECT '1' +  ('1' * 4)
SELECT '1' + '1A' + 5
SELECT 'WILSON' + ' ' + 'SILVA' AS NOME
SELECT 'DEV DOJO' - 2

SELECT 5 + ('4' + '5')

SELECT 2 - '1'

SELECT 2 + 2 AS SOMA,
       2 * 2 AS MULT,
       2 - 2 AS SUB,
       2 % 2 AS RESTO,
       2 / 2 AS DIV